image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - core_api/node_modules/
    - app_front/node_modules/

test_core_api:
  script:
    - cd core_api/
    - npm install
    - npm run test

test_app_front:
  script:
    - cd app_front/
    - npm install
    - npm run test:cli
