version: '3.7'

services:

  # app-front:
  #   container_name: app-front
  #   build: 
  #   context: app-front
  #   dockerfile: Dockerfile
  #   volumes:
  #     - './app-front:/app-front'
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production

  # core-api:
  #   container_name: core-api
  #   build:
  #     context: core-api
  #     dockerfile: Dockerfile
  #     volumes:
  #       - './core-api:/core-api'
  #     ports:
  #       - "8082:8081"

  app-front:
    image: app-front
    build: ./app-front
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  core-api:
    image: core-api
    build: ./core-api
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"  

